import type { SignalSourceRegistryKey } from "@/lib/signal-action-kernel-contract";
import type { SignalSourceRegistryEntry } from "@/lib/signal-source-contract";

export const SIGNAL_SOURCE_REGISTRY: Record<string, SignalSourceRegistryEntry> = {
  ins_tempo: {
    key: "ins_tempo",
    label: "INS Tempo",
    role: "structural",
    category: "demographic",
    accessMode: "official_query_interface",
    authMode: "none",
    runtimeRequirement: "manual_batch",
    trustWeightClass: "high",
    geoResolution: "mixed",
    entityGranularity: "aggregate_market",
    legalUsageClass: "public_conditioned",
    enabledForTruth: true,
    enabledForDistribution: false,
    enabledForReviewIntelligence: false,
    enabledForSupplySaturation: false,
    status: "planned",
    freshnessProfile: {
      recommendedGoodHours: 24 * 90,
      recommendedAcceptableHours: 24 * 365,
      weakAfterHours: 24 * 730,
    },
    industryCoverage: "broad",
    notes: "Sursa structurala oficiala pentru context demografic si teritorial, de obicei agregata pe judet sau regiune.",
  },
  onrc: {
    key: "onrc",
    label: "ONRC Open Data",
    role: "supply",
    category: "registry",
    accessMode: "official_dataset",
    authMode: "none",
    runtimeRequirement: "manual_batch",
    trustWeightClass: "high",
    geoResolution: "mixed",
    entityGranularity: "business_entity",
    legalUsageClass: "public_conditioned",
    enabledForTruth: true,
    enabledForDistribution: false,
    enabledForReviewIntelligence: false,
    enabledForSupplySaturation: true,
    status: "planned",
    freshnessProfile: {
      recommendedGoodHours: 24 * 90,
      recommendedAcceptableHours: 24 * 365,
      weakAfterHours: 24 * 540,
    },
    industryCoverage: "broad",
    notes: "Sursa oficiala pentru densitate de firme, status si acoperire de oferta; buna pentru saturatie, nu pentru trend rapid.",
  },
  google_places: {
    key: "google_places",
    label: "Google Places",
    role: "problem",
    category: "reviews",
    accessMode: "official_api",
    authMode: "api_key",
    runtimeRequirement: "server_required",
    trustWeightClass: "conditional",
    geoResolution: "locality",
    entityGranularity: "review_sample",
    legalUsageClass: "provider_terms_limited",
    enabledForTruth: true,
    enabledForDistribution: false,
    enabledForReviewIntelligence: true,
    enabledForSupplySaturation: true,
    status: "blocked_by_credentials",
    freshnessProfile: {
      recommendedGoodHours: 24 * 30,
      recommendedAcceptableHours: 24 * 90,
      weakAfterHours: 24 * 180,
    },
    industryCoverage: "selective",
    notes: "Util pentru competitor discovery, rating si sampling controlat de reviews; nu trebuie tratat ca stream complet de reviews.",
    requiredSecrets: ["GOOGLE_MAPS_API_KEY"],
  },
  google_trends: {
    key: "google_trends",
    label: "Google Trends",
    role: "demand",
    category: "search_demand",
    accessMode: "official_api",
    authMode: "api_key",
    runtimeRequirement: "server_required",
    trustWeightClass: "conditional",
    geoResolution: "mixed",
    entityGranularity: "search_topic",
    legalUsageClass: "provider_terms_limited",
    enabledForTruth: true,
    enabledForDistribution: false,
    enabledForReviewIntelligence: false,
    enabledForSupplySaturation: false,
    status: "blocked_by_provider_access",
    freshnessProfile: {
      recommendedGoodHours: 24 * 7,
      recommendedAcceptableHours: 24 * 90,
      weakAfterHours: 24 * 180,
    },
    industryCoverage: "broad",
    notes: "Sursa principala de cerere si trend, dar accesul oficial trebuie tratat ca restrictionat pana exista aprobare stabila.",
    requiredSecrets: ["GOOGLE_TRENDS_ACCESS_TOKEN"],
  },
  opportuniq_internal: {
    key: "opportuniq_internal",
    label: "OpportunIQ Internal Events",
    role: "internal",
    category: "platform_activity",
    accessMode: "internal_event_stream",
    authMode: "none",
    runtimeRequirement: "browser_safe",
    trustWeightClass: "medium",
    geoResolution: "mixed",
    entityGranularity: "product_event",
    legalUsageClass: "internal_only",
    enabledForTruth: true,
    enabledForDistribution: true,
    enabledForReviewIntelligence: false,
    enabledForSupplySaturation: false,
    status: "ready",
    freshnessProfile: {
      recommendedGoodHours: 24 * 7,
      recommendedAcceptableHours: 24 * 30,
      weakAfterHours: 24 * 90,
    },
    industryCoverage: "broad",
    notes: "Evenimentele interne influenteaza mai ales distributia si doar marginal adevarul de piata.",
  },
  siruta: {
    key: "siruta",
    label: "SIRUTA / Geo Codification",
    role: "structural",
    category: "geo",
    accessMode: "official_dataset",
    authMode: "none",
    runtimeRequirement: "browser_safe",
    trustWeightClass: "high",
    geoResolution: "locality",
    entityGranularity: "aggregate_market",
    legalUsageClass: "public_reusable",
    enabledForTruth: false,
    enabledForDistribution: false,
    enabledForReviewIntelligence: false,
    enabledForSupplySaturation: false,
    status: "ready",
    freshnessProfile: {
      recommendedGoodHours: 24 * 365,
      recommendedAcceptableHours: 24 * 365 * 3,
      weakAfterHours: 24 * 365 * 5,
    },
    industryCoverage: "broad",
    notes: "Sursa de codificare geografica pentru normalizare, nu pentru adevar economic direct.",
  },
  mfinante: {
    key: "mfinante",
    label: "Ministerul Finantelor",
    role: "structural",
    category: "financial",
    accessMode: "official_query_interface",
    authMode: "account_based",
    runtimeRequirement: "server_required",
    trustWeightClass: "high",
    geoResolution: "national",
    entityGranularity: "business_entity",
    legalUsageClass: "public_conditioned",
    enabledForTruth: true,
    enabledForDistribution: false,
    enabledForReviewIntelligence: false,
    enabledForSupplySaturation: false,
    status: "planned",
    freshnessProfile: {
      recommendedGoodHours: 24 * 180,
      recommendedAcceptableHours: 24 * 365,
      weakAfterHours: 24 * 540,
    },
    industryCoverage: "broad",
    notes: "Poate rafina sanatatea financiara a pietei, dar nu este necesara in prima faza pentru generarea semnalelor locale.",
  },
  seap: {
    key: "seap",
    label: "SEAP",
    role: "demand",
    category: "public_procurement",
    accessMode: "official_query_interface",
    authMode: "account_based",
    runtimeRequirement: "server_required",
    trustWeightClass: "medium",
    geoResolution: "national",
    entityGranularity: "aggregate_market",
    legalUsageClass: "public_conditioned",
    enabledForTruth: true,
    enabledForDistribution: false,
    enabledForReviewIntelligence: false,
    enabledForSupplySaturation: false,
    status: "planned",
    freshnessProfile: {
      recommendedGoodHours: 24 * 30,
      recommendedAcceptableHours: 24 * 90,
      weakAfterHours: 24 * 180,
    },
    industryCoverage: "selective",
    notes: "Sursa complementara pentru goluri de oferta in achizitii publice, nu pentru prima faza retail/local service.",
  },
};

export function getSignalSourceRegistryEntry(key: SignalSourceRegistryKey) {
  return SIGNAL_SOURCE_REGISTRY[key];
}

export function listSignalSourceRegistryEntries(): SignalSourceRegistryEntry[] {
  return Object.values(SIGNAL_SOURCE_REGISTRY);
}
